// Code generated by sql2gorm. DO NOT EDIT.
package models

import (
	"time"

	"gorm.io/gorm"
)

type CarUserInfo struct {
	ID          int       `gorm:"column:id;type:int(11);primary_key;AUTO_INCREMENT" json:"id"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreateAt    time.Time `gorm:"column:create_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"create_at"`
	Vin         string    `gorm:"column:vin;type:varchar(17);NOT NULL" json:"vin"`
	CarType     string    `gorm:"column:car_type;type:varchar(255);NOT NULL" json:"car_type"`
	UseType     string    `gorm:"column:use_type;type:varchar(255);NOT NULL" json:"use_type"`
	NowerName   string    `gorm:"column:nower_name;type:varchar(255);default:none" json:"nower_name"`
	Priority    int       `gorm:"column:priority;type:int(11)" json:"priority"`
	ProjectName string    `gorm:"column:project_name;type:varchar(255)" json:"project_name"`
}

func (m *CarUserInfo) TableName() string {
	return "car_user_info"
}


func FindUseTypeOfVinAndTime(db *gorm.DB, vin string, dateTime string) (data CarUserInfo, err error) {
	err = db.Table("car_user_info").
	Where("vin = ? and CreateAt <= ?",vin,dateTime).
	First(&data).Error
	return
}